version: '3.7'
services:
  mongo:
    image: mongo
    container_name: "allero-mongo-db"
    command: mongod --auth
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - './dockervolume/mongodb:/data/db'
    ports:
      - 27017:27017